//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKhachSanEntities : DbContext
    {
        public QLKhachSanEntities()
            : base("name=QLKhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblctdatphong> tblctdatphongs { get; set; }
        public virtual DbSet<tblctthuephong> tblctthuephongs { get; set; }
        public virtual DbSet<tbldichvu> tbldichvus { get; set; }
        public virtual DbSet<tblhoadon> tblhoadons { get; set; }
        public virtual DbSet<tblkhachhang> tblkhachhangs { get; set; }
        public virtual DbSet<tblloaiphong> tblloaiphongs { get; set; }
        public virtual DbSet<tblnhanvien> tblnhanviens { get; set; }
        public virtual DbSet<tblphieudatphong> tblphieudatphongs { get; set; }
        public virtual DbSet<tblphieuthuephong> tblphieuthuephongs { get; set; }
        public virtual DbSet<tblphong> tblphongs { get; set; }
        public virtual DbSet<tbltrangthaiphong> tbltrangthaiphongs { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblvattu> tblvattus { get; set; }
    }
}
